<a href="https://colab.research.google.com/github/sisbhumi/MachineLearning/blob/main/Numpytuttorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a=np.array([[[1,2,3,9],[3,4,5,10],[6,7,8,10]],[[1,2,3,10],[3,4,5,10],
[6,7,8,10]],[[1,2,3,10],[3,4,5,10],[6,7,8,10]]])

print(a.ndim)

print(a.shape)

print(a.size)

a=np.arange(24).reshape(2,3,4)

a.resize(3,8)

print(a)

In [ ]:
b = np.array([[1.5,2,3], [4,5,6]])
c = np.array( [ [1,2], [3,4] ], dtype=complex )

print(b)
print(b.dtype)

print(c)

In [ ]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )    # type of array explicitly defined
c


In [ ]:
c=np.empty( (2,3) )
print(c)
b=np.ones( (2,3,4), dtype=np.int16 ) 
b

In [ ]:
b=np.ones( (2,3,4), dtype=np.int16 )
n=np.empty((2,5))
print(n)


In [ ]:
   
c=np.linspace( 0, 2, 9 )
ca=np.arange( 0, 2, 9 )
b=np.linspace( 0, 2, 5 )
ba=np.arange( 0, 2, 5 )
a=np.linspace( 0, 2, 20 )


aa=np.arange( 0, 2, 20 )



print(a ,aa ,b,ba,c,ca, sep='\n') 

In [ ]:
import numpy as np 
a = np.array([0,30,45,60,90]) 

print('Sine of different angles:' )
# Convert to radians by multiplying with pi/180 
print(np.sin(a*np.pi/180) )
print('\n' ) 

print( 'Cosine values for angles in array:' )
print(np.cos(a*np.pi/180))
print ('\n' ) 

print('Tangent values for given angles:' )
print(np.tan(a*np.pi/180))

In [ ]:
# Create an array with random values 
e = np.random.random((2, 2)) 
print ("\nA random array:\n", e) 
  
# Create a sequence of integers  
# from 0 to 30 with steps of 5 
f = np.arange(0, 30, 5) 
print ("\nA sequential array with steps of 5:\n", f) 
  
# Create a sequence of 10 values in range 0 to 5 
g = np.linspace(0, 5, 10) 
print ("\nA sequential array with 10 values between"
                                        "0 and 5:\n", g) 
  
# Reshaping 3X4 array to 2X2X3 array 
arr = np.array([[1, 2, 3, 4], 
                [5, 2, 4, 2], 
                [1, 2, 0, 1]]) 
  
newarr = arr.reshape(2, 2, 3) 
  
print ("\nOriginal array:\n", arr) 
print ("Reshaped array:\n", newarr) 
  
# Flatten array 
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
flarr = arr.flatten() 
  
print ("\nOriginal array:\n", arr) 
print ("Fattened array:\n", flarr) 


A random array:
 [[0.93534581 0.47483734]
 [0.19025066 0.68518121]]

A sequential array with steps of 5:
 [ 0  5 10 15 20 25]

A sequential array with 10 values between0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]

Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


Flatten array: We can use flatten method to get a copy of array collapsed into one dimension. It accepts order argument. Default value is ‘C’ (for row-major order). 
Use ‘F’ for column major order.

Stacking: Several arrays can be stacked together along different axes.

np.vstack: To stack arrays along vertical axis.

np.hstack: To stack arrays along horizontal axis.

np.column_stack: To stack 1-D arrays as columns into 2-D arrays.
np.concatenate: To stack arrays along specified axis (axis is passed as argument).

In [ ]:
import numpy as np
  
a = np.array([[1, 2], 
              [3, 4]]) 
  
b = np.array([[5, 6], 
              [7, 8]]) 
  
# vertical stacking 
print("Vertical stacking:\n", np.vstack((a, b))) 
  
# horizontal stacking 
print("\nHorizontal stacking:\n", np.hstack((a, b))) 
  
c = [5, 6] 
  
# stacking columns 
print("\nColumn stacking:\n", np.column_stack((a, c))) 
  
# concatenation method  
print("\nConcatenating to 2nd axis:\n", np.concatenate((a, b), 1)) 


Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]

Column stacking:
 [[1 2 5]
 [3 4 6]]

Concatenating to 2nd axis:
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Splitting:For splitting, we have these functions:
np.hsplit: Split array along horizontal axis.
np.vsplit: Split array along vertical axis.
np.array_split: Split array along specified axis.




In [ ]:
import numpy as np 
  
a = np.array([[1, 3, 5, 7, 9, 11], 
              [2, 4, 6, 8, 10, 12]]) 
  
# horizontal splitting 
print("Splitting along horizontal axis into 2 parts:\n", np.hsplit(a, 2)) 
  
# vertical splitting 
print("\nSplitting along vertical axis into 2 parts:\n", np.vsplit(a, 2))

Splitting along horizontal axis into 2 parts:
 [array([[1, 3, 5],
       [2, 4, 6]]), array([[ 7,  9, 11],
       [ 8, 10, 12]])]

Splitting along vertical axis into 2 parts:
 [array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]


In [ ]:
# broadcasting Strenching array
import numpy as np 
  
a = np.array([0.0, 10.0, 20.0, 30.0])

b = np.array([0.0, 1.0, 2.0,5.0]) 

  
print(a + b)

In [ ]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, 3, 4)
print(a)
print(b)
print(a.sum(), b.min(), b.max())

In [ ]:
import numpy as np
ar=np.array[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]][[13,14,15][16,17,18]]
